baseURL: 'https://2022.ubucon.asia/'
languageCode: en-us
title: UbuCon Asia 2022
theme: ubuconasia
Paginate: 5
buildFuture: true
enableRobotsTXT: true
enableGitInfo: true
defaultContentLanguage: en
languages:
  ko:
    languageName: 한국어
    title: 우부콘 아시아 2022
    weight: 2
    params:
      descriptionOnHomepage: >-
        한국에서 열리는 첫 오프라인 우분투 아시아 컨퍼런스.
      description: 11월 26일 ~ 27일 | 서울 상암동 누리꿈스퀘어
      period: 2022년 11월 26일 ~ 27일 | 서울 상암동 누리꿈스퀘어
      venueName: 누리꿈스퀘어 3~4층
    menu:
      main:
        - identifier: about
          name: 소개
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: 행사장 및 여행정보
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: 행사장/안전정보
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: 입국요건과 비자
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-sponsorship
          parent: venue-travel-group
          name: 여행 경비 지원
          url: venue-and-travel/travel-sponsorship
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: 근처 숙박시설
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: tourism
          parent: venue-travel-group
          name: 관광정보
          url: venue-and-travel/tourism
          weight: 25
        - identifier: visitseoul
          parent: venue-travel-group
          name: VisitSeoul.net
          url: https://korean.visitseoul.net
          weight: 26
        - identifier: programs-group
          name: 프로그램
          url: programs
          weight: 30
        - identifier: call-for-proposals
          parent: programs-group
          name: 발표 제안
          url: call-for-proposals
          weight: 31
        - identifier: sessions
          parent: programs-group
          name: 세션
          url: sessions
          weight: 32
        - identifier: social-events
          parent: programs-group
          name: 부대행사
          url: social-events
          weight: 33
        - identifier: sponsors-group
          name: 후원사/개인후원
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: 후원사 등록 안내
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: 후원사
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: 개인 후원자
          url: patrons
          weight: 43
        - identifier: news
          name: 소식
          url: news
          weight: 50
        - identifier: wiki
          name: 위키
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 60
  en:
    languageName: English
    title: UbuCon Asia 2022
    weight: 1
    params:
      descriptionOnHomepage: >-
        The first In-person Ubuntu Asia conference in South Korea.
      description: November 26th ~ 27th | Nuritkum Square, Seoul, South Korea
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
      venueName: Nuritkum Square 3F~4F
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-sponsorship
          parent: venue-travel-group
          name: Travel sponsorship
          url: venue-and-travel/travel-sponsorship
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: tourism
          parent: venue-travel-group
          name: Tourism
          url: venue-and-travel/tourism
          weight: 25
        - identifier: visitseoul
          parent: venue-travel-group
          name: VisitSeoul.net
          url: https://english.visitseoul.net/index
          weight: 26
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 30
        - identifier: call-for-proposals
          parent: programs-group
          name: Call for proposals
          url: call-for-proposals
          weight: 31
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 32
        - identifier: social-events
          parent: programs-group
          name: Social events
          url: social-events
          weight: 33
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 43
        - identifier: news
          name: News
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 60
  id:
    languageName: Bahasa Indonesia
    title: UbuCon Asia 2022
    weight: 2
    params:
      descriptionOnHomepage: >-
        The first In-person Ubuntu Asia conference in South Korea.
      description: November 26th ~ 27th | Nuritkum Square, Seoul, South Korea
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
      venueName: Nuritkum Square 3F~4F
    menu:
      main:
        - identifier: about
          name: Tentang
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-sponsorship
          parent: venue-travel-group
          name: Travel sponsorship
          url: venue-and-travel/travel-sponsorship
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: tourism
          parent: venue-travel-group
          name: Tourism
          url: venue-and-travel/tourism
          weight: 25
        - identifier: visitseoul
          parent: venue-travel-group
          name: VisitSeoul.net
          url: https://english.visitseoul.net/index
          weight: 26
        - identifier: programs-group
          name: Program
          url: programs
          weight: 30
        - identifier: call-for-proposals
          parent: programs-group
          name: Call for proposals
          url: call-for-proposals
          weight: 31
        - identifier: sessions
          parent: programs-group
          name: Sesi
          url: sessions
          weight: 32
        - identifier: social-events
          parent: programs-group
          name: Social events
          url: social-events
          weight: 33
        - identifier: sponsors-group
          name: Sponsor/Patron
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsor
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Patron Individual
          url: patrons
          weight: 43
        - identifier: news
          name: Berita
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 60
  ja:
    languageName: 日本語
    title: UbuCon Asia 2022
    weight: 3
    params:
      descriptionOnHomepage: >-
        The first In-person Ubuntu Asia conference in South Korea.
      description: November 26th ~ 27th | Nuritkum Square, Seoul, South Korea
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
      venueName: Nuritkum Square 3F~4F
    menu:
      main:
        - identifier: about
          name: Ubucon Asiaとは
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-sponsorship
          parent: venue-travel-group
          name: Travel sponsorship
          url: venue-and-travel/travel-sponsorship
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: tourism
          parent: venue-travel-group
          name: Tourism
          url: venue-and-travel/tourism
          weight: 25
        - identifier: visitseoul
          parent: venue-travel-group
          name: VisitSeoul.net
          url: https://japanese.visitseoul.net/
          weight: 26
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 30
        - identifier: call-for-proposals
          parent: programs-group
          name: Call for proposals
          url: call-for-proposals
          weight: 31
        - identifier: sessions
          parent: programs-group
          name: セッション
          url: sessions
          weight: 32
        - identifier: social-events
          parent: programs-group
          name: Social events
          url: social-events
          weight: 33
        - identifier: sponsors-group
          name: スポンサー/Patrons
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: スポンサー
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 43
        - identifier: news
          name: ニュース
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 60
  zh-hant-tw:
    languageName: 正體中文(臺灣)
    title: UbuCon Asia 2022
    weight: 2
    params:
      descriptionOnHomepage: >-
        The first In-person Ubuntu Asia conference in South Korea.
      description: November 26th ~ 27th | Nuritkum Square, Seoul, South Korea
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
      venueName: Nuritkum Square 3F~4F
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: Venue & Safety
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-sponsorship
          parent: venue-travel-group
          name: Travel sponsorship
          url: venue-and-travel/travel-sponsorship
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: tourism
          parent: venue-travel-group
          name: Tourism
          url: venue-and-travel/tourism
          weight: 25
        - identifier: visitseoul
          parent: venue-travel-group
          name: VisitSeoul.net
          url: https://tchinese.visitseoul.net/
          weight: 26
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 30
        - identifier: call-for-proposals
          parent: programs-group
          name: Call for proposals
          url: call-for-proposals
          weight: 31
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 32
        - identifier: social-events
          parent: programs-group
          name: Social events
          url: social-events
          weight: 33
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 40
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 41
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 43
        - identifier: news
          name: News
          url: news
          weight: 50
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 60
  zh-hans-cn:
    languageName: 简体中文（中国大陆）
    title: UbuCon Asia 2022
    weight: 3
    params:
      descriptionOnHomepage: >-
        首次在韩国举行的 Ubuntu 亚洲峰会。
      description: 11 月 26 至 27 日  | 韩国，首尔市，Nuritkum Square
      period: 2022 年 11 月 26 至 27 日  | 韩国，首尔市，Nuritkum Square
      venueName: Nuritkum Square 3F~4F
    menu:
      main:
        - identifier: about
          name: 关于 Ubucon Asia
          url: about
          weight: 10
        - identifier: venue-travel-group
          name: 场馆指南
          url: venue-and-travel
          weight: 20
        - identifier: venue
          parent: venue-travel-group
          name: 场馆介绍
          url: venue-and-travel/venue-and-safety
          weight: 21
        - identifier: entry-and-visa
          parent: venue-travel-group
          name: Entry requirements and Visa
          url: venue-and-travel/entry-and-visa
          weight: 22
        - identifier: travel-sponsorship
          parent: venue-travel-group
          name: Travel sponsorship
          url: venue-and-travel/travel-sponsorship
          weight: 23
        - identifier: accommodations
          parent: venue-travel-group
          name: Accomodations
          url: venue-and-travel/accommodations
          weight: 24
        - identifier: tourism
          parent: venue-travel-group
          name: Tourism
          url: venue-and-travel/tourism
          weight: 25
        - identifier: visitseoul
          parent: venue-travel-group
          name: VisitSeoul.net
          url: https://chinese.visitseoul.net/index
          weight: 26
        - identifier: programs-group
          name: 会议
          url: programs
          weight: 30
        - identifier: call-for-proposals
          parent: programs-group
          name: Call for proposals
          url: call-for-proposals
          weight: 31
        - identifier: sessions
          parent: programs-group
          name: 会议流程
          url: sessions
          weight: 32
        - identifier: social-events
          parent: programs-group
          name: Social events
          url: social-events
          weight: 33
        - identifier: sponsors-group
          name: 赞助商
          url: sponsors
          weight: 40
        - identifier: sponsors
          parent: sponsors-group
          name: 赞助商
          url: sponsors
          weight: 41
        - identifier: become-a-sponsor
          parent: sponsors-group
          name: Become a sponsor
          url: become-a-sponsor
          weight: 42
        - identifier: patrons
          parent: sponsors-group
          name: 个人赞助者
          url: patrons
          weight: 43
        - identifier: news
          name: 新闻
          url: news
          weight: 44
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 50
params:
  contact: contact@ubucon.asia
  calendarOrganizer: UbuCon Asia 2022 Organizers
  calendarUidSuffix: 2022.asia.ubucon.org
  facebook: ubuconasia
  twitter: ubuconasia
  github: ubucon-asia
  repo: https://github.com/ubucon-asia/2022
  cloudflareAnalyticsToken: 25b3a95f0c9b46ebbe67afb9ea6006b2
  copyright:  >-
    © 2022 UbuCon Asia 2022 Website authors.
    Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY 4.0. 
    Ubuntu and Canonical are registered trademarks of Canonical Ltd.
  email: contact@ubucon.asia
  registerURLs:
    attendee: https://eventyay.com/e/75ac7f83
    callForSpeakers: /cfs
  timetable:
    dateStart: 2022-11-26T10:00:00+09:00
    dateEnd: 2022-11-27T18:00:00+09:00
    timeStart: 2000-01-01T09:00:00+09:00 # Use random date for timeStart param
  eventInfo:
    virtualLocationUrl: https://www.youtube.com/channel/UCdy5ggH4LKgUyr0WIH9DPwQ
    streetAddress: "396, World Cup buk-ro"
    addressLocality: "Mapo-gu"
    postalCode: "03925"
    addressRegion: "Seoul"
    addressCountry: "KR"
outputs:
  home: ["HTML", "RSS", "Calendar", "JSON"]
markup:
  goldmark:
    renderer:
      unsafe: true